### ISSUE TITLE
utterances theme

### ISSUE THREAD

**Issue by Alfxjx** [StreakingMan/streakingman.com#1]
[this may help](https://github.com/Alfxjx/Alfxjx.github.io/blob/master/components/Comments/index.tsx), using theming context in utterances and next.js

**Comment by StreakingMan** [comment]
嗯感谢🤠，可以这样操作。但我刚翻了下issue发现utterance支持 [postMessage的方式](https://github.com/utterance/utterances/issues/549#issuecomment-907606127)
